name: Publish on GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 14
        
      - name: Install dependencies #nodes (no python)
        run: |
          npm install
          npm run build
      
      #- name: Build html 
       # run: |
        #  make html
         # rm -r build/html/_sources 
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      
      #- name: Next static build and export with HTML/JS minification
      #  uses: tsg-iitkgp/next-build-export-action@v1.2.1
      
      - name: Publish to GitHub Pages
        uses: tsunematsu21/actions-publish-gh-pages@v1.0.2


