name: Publish on GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.2.0
        with:
          node-version: 14
        
      - name: Install dependencies #nodes (no python)
        run: |
          npm ci
          npm run build
      
      - name: Publish on GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: build
